apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: pv-blob-input
spec:
  capacity:
    storage: 4096Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - -o allow_other
    - --block-cache
    - --block-cache-block-size=16
    - --block-cache-disk-size=50000
    - --block-cache-parallelism=36
    - --block-cache-prefetch=128
    - --use-adls=true
  csi:
    driver: blob.csi.azure.com
    # volumeid has to be unique for every identical storage blob container in the cluster
    # character `#`and `/` are reserved for internal use and cannot be used in volumehandle
    volumeHandle: ${INPUT_STORAGE_ACCOUNT}_input
    volumeAttributes:
      protocol: fuse2
      storageAccount: $INPUT_STORAGE_ACCOUNT
      containerName: input
      use-adls: "true"
    nodeStageSecretRef:
      name: azure-sas-token-input
      namespace: default
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: pv-blob-output
spec:
  capacity:
    storage: 4096Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  # If set as "Delete" container would be removed after pvc deletion
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - -o allow_other
    - --block-cache
    - --block-cache-block-size=16
    - --block-cache-disk-size=50000
    - --block-cache-parallelism=36
    - --block-cache-prefetch=128
    - --use-adls=true
  csi:
    driver: blob.csi.azure.com
    # volumeid has to be unique for every identical storage blob container in the cluster
    # character `#`and `/` are reserved for internal use and cannot be used in volumehandle
    volumeHandle: ${OUTPUT_STORAGE_ACCOUNT}_output
    volumeAttributes:
      protocol: fuse2
      storageAccount: $OUTPUT_STORAGE_ACCOUNT
      containerName: output
      use-adls: "true"
    nodeStageSecretRef:
      name: azure-sas-token-output
      namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob-input
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 4096Gi
  volumeName: pv-blob-input
  storageClassName: azureblob-fuse-premium
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob-output
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4096Gi
  volumeName: pv-blob-output
  storageClassName: azureblob-fuse-premium